version: "3"
services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: to_do
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: