version: "3"
services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: to_do
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend: 
    container_name: backend
    build: ./todoback
    command: sh -c "yarn run typeorm:migration:run:docker && yarn run start"
    ports:
      - 8000:8000
    volumes:
      - ./todoback:/backApp
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: ./React_To-Do
    ports: 
      - 3000:3000
    depends_on:
      - backend

volumes:
  pgdata: