export enum AnswerEnum {
  CLIENT_SUCCESS = 'Клиент подтвержден!',
  CLIENT_NO_SUCCESS = 'Клиент не подтвержден!',
  PASS_ADD = 'Пароль установлен!',
  PASS_AND_EMAIL_ADD = 'Пароль и почта установлены!',
  SEND_MAIL = 'Письмо со ссылкой для сброса пароля успешно отправлено на почту!',
  SAVE_FILE = 'Файлы получены!',
  USERS_ADD = 'Пользователи добавлены!',
  USERS_NO_ADD = 'Нет новых Пользователи!',
  PRODUCT_ADD = 'Продукты добавлены!',
  PRODUCT_NO_ADD = 'Нет новых Продуктов!',
  BRAND_DELETE = 'Бренд удален!',
  CATALOG_DELETE = 'Категория товара удалена!',
  SUB_CATALOG_DELETE = 'Под Категория товара удалена!',
  CATEGORY_DELETE = 'Категория протокола удалена!',
  PROTOCOL_DELETE = 'Протокол удален!',
}
